name: Nix Build

on:
  - push
  - pull_request
  - release

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - uses: cachix/install-nix-action@v22
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        extra_nix_config: |
          experimental-features = nix-command flakes
          allow-import-from-derivation = true
          accept-flake-config = true

    - uses: cachix/cachix-action@v12
      with:
        name: sgillespie
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Build executables (Linux)
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        # Static build x86_64
        nix build -L .\#x86_64-unknown-linux-musl:lox-server:exe:lox-server -o lox-server-linux-x86_64
        # Static cross build aarch64
        nix build -L .\#aarch64-unknown-linux-musl:lox-server:exe:lox-server -o lox-server-linux-aarch64
        # Windows cross build
        nix build -L .\#x86_64-w64-mingw32:lox-server:exe:lox-server -o lox-server-windows-x86_64

    - name: Build executables (macOS)
      if: ${{ matrix.os == 'macos-latest' }}
      run: |
        # Native build aarch64
        nix build -L .\#lox-server:exe:lox-server -o lox-server-macos-aarch64

    - name: Run tests (Linux)
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        nix build -L .\#checks.x86_64-linux.lox-server:test:lox-server-test

    - name: Run tests (macOS)
      if: ${{ matrix.os == 'macos-latest' }}
      run: |
        nix build -L .\#checks.aarch64-darwin.lox-server:test:lox-server-test


    - name: Upload release artifacts
      uses: softprops/action-gh-release@v2
      if: ${{ github.event_name == 'release' }}
      with:
        files: |
          lox-server-linux-x86_64
          lox-server-linux-aarch64
          lox-server-windows-x86_64
          lox-server-macos-aarch64
